use super::eslint;

/// See https://github.com/jest-community/eslint-plugin-jest/blob/main/src/index.ts
pub(crate) const RECOMMENDED: [(&str, eslint::Severity); 19] = [
    ("jest/expect-expect", eslint::Severity::Warn),
    ("jest/no-alias-methods", eslint::Severity::Error),
    ("jest/no-commented-out-tests", eslint::Severity::Warn),
    ("jest/no-conditional-expect", eslint::Severity::Error),
    ("jest/no-deprecated-functions", eslint::Severity::Error),
    ("jest/no-disabled-tests", eslint::Severity::Warn),
    ("jest/no-done-callback", eslint::Severity::Error),
    ("jest/no-export", eslint::Severity::Error),
    ("jest/no-focused-tests", eslint::Severity::Error),
    ("jest/no-identical-title", eslint::Severity::Error),
    (
        "jest/no-interpolation-in-snapshots",
        eslint::Severity::Error,
    ),
    ("jest/no-jasmine-globals", eslint::Severity::Error),
    ("jest/no-mocks-import", eslint::Severity::Error),
    ("jest/no-standalone-expect", eslint::Severity::Error),
    ("jest/no-test-prefixes", eslint::Severity::Error),
    ("jest/valid-describe-callback", eslint::Severity::Error),
    ("jest/valid-expect", eslint::Severity::Error),
    ("jest/valid-expect-in-promise", eslint::Severity::Error),
    ("jest/valid-title", eslint::Severity::Error),
];

pub(crate) const NON_RECOMMENDED_ERROR: [(&str, eslint::Severity); 36] = [
    ("jest/consistent-test-it", eslint::Severity::Error),
    ("jest/expect-expect", eslint::Severity::Error),
    ("jest/max-expects", eslint::Severity::Error),
    ("max-nested-describe", eslint::Severity::Error),
    ("no-commented-out-tests", eslint::Severity::Error),
    ("no-conditional-in-test", eslint::Severity::Error),
    ("no-confusing-set-timeout", eslint::Severity::Error),
    ("no-disabled-tests", eslint::Severity::Error),
    ("no-duplicate-hooks", eslint::Severity::Error),
    ("no-hooks", eslint::Severity::Error),
    ("no-if", eslint::Severity::Error),
    ("no-large-snapshots", eslint::Severity::Error),
    ("no-restricted-jest-methods", eslint::Severity::Error),
    ("no-restricted-matchers", eslint::Severity::Error),
    ("no-test-return-statement", eslint::Severity::Error),
    ("no-untyped-mock-factory", eslint::Severity::Error),
    ("prefer-called-with", eslint::Severity::Error),
    ("prefer-comparison-matcher", eslint::Severity::Error),
    ("prefer-each", eslint::Severity::Error),
    ("prefer-equality-matcher", eslint::Severity::Error),
    ("prefer-expect-assertions", eslint::Severity::Error),
    ("prefer-expect-resolves", eslint::Severity::Error),
    ("prefer-hooks-in-order", eslint::Severity::Error),
    ("prefer-hooks-on-top", eslint::Severity::Error),
    ("prefer-lowercase-title", eslint::Severity::Error),
    ("prefer-mock-promise-shorthand", eslint::Severity::Error),
    ("prefer-snapshot-hint", eslint::Severity::Error),
    ("prefer-spy-on", eslint::Severity::Error),
    ("prefer-strict-equal", eslint::Severity::Error),
    ("prefer-to-be", eslint::Severity::Error),
    ("prefer-to-contain", eslint::Severity::Error),
    ("prefer-to-have-length", eslint::Severity::Error),
    ("prefer-todo", eslint::Severity::Error),
    ("require-hook", eslint::Severity::Error),
    ("require-to-throw-message", eslint::Severity::Error),
    ("require-top-level-describe", eslint::Severity::Error),
];

pub(crate) const STYLE: [(&str, eslint::Severity); 4] = [
    ("jest/no-alias-methods", eslint::Severity::Warn),
    ("jest/prefer-to-be", eslint::Severity::Error),
    ("jest/prefer-to-contain", eslint::Severity::Error),
    ("jest/prefer-to-have-length", eslint::Severity::Error),
];
